In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx')

In [3]:
df.shape

(10000, 17)

In [4]:
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [5]:
df['TOTAL_SEATS'] = (df["FIRST_CLASS_SEATS"] + df["BUSINESS_CLASS_SEATS"] + df["ECONOMY_SEATS"])
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,TOTAL_SEATS
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38,235
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28,235
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40,180
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54,180
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27,180

In [6]:
df["TIER1_PCT"] = (df["TIER1_ELIGIBLE_PAX"] / df["TOTAL_SEATS"]) * 100
df["TIER2_PCT"] = (df["TIER2_ELIGIBLE_PAX"] / df["TOTAL_SEATS"]) * 100
df["TIER3_PCT"] = (df["TIER3_ELIGIBLE_PAX"] / df["TOTAL_SEATS"]) * 100

In [8]:
df[
    [
        "FLIGHT_NO",
        "HAUL",
        "TOTAL_SEATS",
        "TIER1_ELIGIBLE_PAX",
        "TIER1_PCT",
        "TIER3_PCT",
    ]
].head()

  FLIGHT_NO   HAUL  TOTAL_SEATS  TIER1_ELIGIBLE_PAX  TIER1_PCT  TIER3_PCT
0    BA5211   LONG          235                   0        0.0  16.170213
1    BA7282   LONG          235                   0        0.0  11.914894
2    BA1896  SHORT          180                   0        0.0  22.222222
3    BA5497  SHORT          180                   0        0.0  30.000000
4    BA1493  SHORT          180                   0        0.0  15.000000

In [11]:
lookup_table = (
    df.groupby(['HAUL','TIME_OF_DAY'])[
    ["TIER1_PCT", "TIER2_PCT", "TIER3_PCT"]
    ]
    .mean()
    .reset_index()
)

In [14]:
lookup_table["TOTAL_ELIGIBLE_PCT"] = (
    lookup_table["TIER1_PCT"]
    + lookup_table["TIER2_PCT"]
    + lookup_table["TIER3_PCT"]
)

In [15]:
lookup_table["Category"] = (
    lookup_table["HAUL"].replace(
        {"SHORT": "Short-haul", "LONG": "Long-haul"}
    )
    + " "
    + lookup_table["TIME_OF_DAY"]
)

In [16]:
numeric_cols = [
    "TIER1_PCT",
    "TIER2_PCT",
    "TIER3_PCT",
    "TOTAL_ELIGIBLE_PCT",
]
lookup_table[numeric_cols] = lookup_table[numeric_cols].round(2)

In [18]:
print("============  BRITISH AIRWAYS LOUNGE ELIGIBILITY LOOKUP TABLE ===========")
display(
    lookup_table[
        [
            "Category",
            "TIER1_PCT",
            "TIER2_PCT",
            "TIER3_PCT",
            "TOTAL_ELIGIBLE_PCT",
        ]
    ]
)

============  BRITISH AIRWAYS LOUNGE ELIGIBILITY LOOKUP TABLE ===========

               Category  TIER1_PCT  TIER2_PCT  TIER3_PCT  TOTAL_ELIGIBLE_PCT
0   Long-haul Afternoon       0.21       2.94      11.17               14.32
1     Long-haul Evening       0.23       2.86      10.97               14.07
2   Long-haul Lunchtime       0.19       2.89      11.06               14.14
3     Long-haul Morning       0.22       2.95      11.25               14.43
4  Short-haul Afternoon       0.34       4.31      16.59               21.24
5    Short-haul Evening       0.33       4.45      17.00               21.78
6  Short-haul Lunchtime       0.39       4.55      17.28               22.22
7    Short-haul Morning       0.34       4.36      16.74               21.44

In [20]:
lookup_table.head()

,HAUL,TIME_OF_DAY,TIER1_PCT,TIER2_PCT,TIER3_PCT,TOTAL_ELIGIBLE_PCT,Category
0,LONG,Afternoon,0.21,2.94,11.17,14.32,Long-haul Afternoon
1,LONG,Evening,0.23,2.86,10.97,14.07,Long-haul Evening
2,LONG,Lunchtime,0.19,2.89,11.06,14.14,Long-haul Lunchtime
3,LONG,Morning,0.22,2.95,11.25,14.43,Long-haul Morning
4,SHORT,Afternoon,0.34,4.31,16.59,21.24,Short-haul Afternoon

In [21]:
sample_indices = [1, 9, 8, 2, 0, 7, 3, 4, 5, 6]
sample_df = df.iloc[sample_indices].copy()

sample_df["Category"] = (
    sample_df["HAUL"].replace({"SHORT": "Short-haul", "LONG": "Long-haul"})
    + " "
    + sample_df["TIME_OF_DAY"]
)

In [23]:
sample_df["Tier 1 %"] = sample_df["TIER1_PCT"].round(1).astype(str) + "%"
sample_df["Tier 2 %"] = sample_df["TIER2_PCT"].round(1).astype(str) + "%"
sample_df["Tier 3 %"] = sample_df["TIER3_PCT"].round(1).astype(str) + "%"

In [26]:
columns_to_show = [
    "FLIGHT_NO",
    "FLIGHT_TIME",
    "ARRIVAL_STATION_CD",
    "Category",
    "Tier 1 %",
    "Tier 2 %",
    "Tier 3 %",
]
print("================== SAMPLE FLIGHT SCHEDULE WITH ESTIMATED ELIGIBILITY =====================")
display(sample_df[columns_to_show])

================== SAMPLE FLIGHT SCHEDULE WITH ESTIMATED ELIGIBILITY =====================

,FLIGHT_NO,FLIGHT_TIME,ARRIVAL_STATION_CD,Category,Tier 1 %,Tier 2 %,Tier 3 %
1,BA7282,06:42:00,LAX,Long-haul Morning,0.0%,3.0%,11.9%
9,BA4878,09:55:00,IST,Short-haul Morning,0.6%,6.1%,21.7%
8,BA4424,12:13:00,FRA,Short-haul Lunchtime,0.0%,2.8%,12.8%
2,BA1896,15:33:00,FRA,Short-haul Afternoon,0.0%,6.1%,22.2%
0,BA5211,14:19:00,LAX,Long-haul Afternoon,0.0%,4.3%,16.2%
7,BA7116,14:50:00,ORD,Long-haul Afternoon,0.3%,3.6%,12.7%
3,BA5497,18:29:00,IST,Short-haul Evening,0.0%,8.9%,30.0%
4,BA1493,20:35:00,FRA,Short-haul Evening,0.0%,3.3%,15.0%
5,BA4954,19:08:00,VIE,Short-haul Evening,0.0%,3.3%,15.0%
6,BA9840,21:44:00,AMS,Short-haul Evening,0.0%,8.9%,30.6%